### ISSUE TITLE
RHEL7 RPM Conflict

### ISSUE THREAD

**Issue by aepod** [zend-patterns/ZendServerPuppet#8]
```Error: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install zend-server-nginx-php-5.5' returned 1: Transaction check error:         
  file /etc/nginx/fastcgi.conf conflicts between attempted installs of zend-server-nginx-php-5.5-8.0.2-388.x86_64 and nginx-1:1.6.3-1.el7.x86
_64 ```

This is because the /etc/nginx/fastcgi.conf is in both zend-server-nginx-php-5.5-8.0.2-388.x86_64.rpm  supplied from Zend Repo and the EPEL Nginx rpm supplied by epel.

Using Redhat 7.1, on a clean install.

**Comment by mkherlakian** [comment]
@aepod following Twitter exchange, I'm writing the info here to have a history on the issue.

The problem you are referring to is due to the fact that the Zend Server install requires the nginx distribution available from nginx.org (at http://nginx.org/packages/). You mentioned you would be able to make the change and submit a PR, which would be great. Let me know if that changed, I'll have someone look at it otherwise on our end.
Thanks!

**Comment by aepod** [comment]
Yes, this was able to solve this issue. I am going to make a PR that covers only adding documentation, so that this is reflected.

Also note that even with the repo added, I ran into issues at at a later step in the process. I will make note of it as a separate issue... today, or perhaps tomorrow.

**Comment by aepod** [comment]
PR #9 should close this issue for now.

**Comment by mkherlakian** [comment]
Thanks @aepod!
